# Generated by Django 5.1.1 on 2025-05-27 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('idFuncionario', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('nome', models.CharField(max_length=100)),
                ('funcao', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Linha',
            fields=[
                ('idLinha', models.IntegerField(unique=True)),
                ('nomeLinha', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Passagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPassagem', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('usosDisponiveis', models.PositiveIntegerField(default=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passagens', to='app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datahora', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_empresa.funcionario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
                ('passagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_empresa.passagem')),
            ],
        ),
    ]
