# Generated by Django 5.1.1 on 2025-05-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_empresa', '0002_linha_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linha',
            name='id',
        ),
        migrations.AlterField(
            model_name='linha',
            name='idLinha',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
