# Generated by Django 5.1.1 on 2025-05-27 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_empresa', '0003_remove_linha_id_alter_linha_idlinha'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='linha',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_empresa.linha'),
            preserve_default=False,
        ),
    ]
