# Generated by Django 5.1.1 on 2025-05-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idTelUsuario', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
